spring:
  datasource:
    url: jdbc:mysql://localhost:5432/student_management
    username: root
    password: '@Potter77'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generateDdl: true
    showSql: true
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  openapi-ui:
    path: /openapi-ui.html

server:
  port: 8080